-- Creación de la base de datos
CREATE DATABASE TALLER_JAFET;
GO


USE TALLER_JAFET;
-- Tablas
CREATE TABLE CLIENTE (
    IDCLIENTE INT IDENTITY PRIMARY KEY,
    NOMBRECLIENTE VARCHAR(200),
    TELEFONOCLIENTE VARCHAR(200),
    CEDULACLIENTE VARCHAR(200) UNIQUE,
	CORREOCLIENTE VARCHAR(200)
);



CREATE TABLE ADMINISTRADOR (
    IDADMINISTRADOR INT IDENTITY PRIMARY KEY,
    NOMBREADMINISTRADOR VARCHAR(200),
    TELEFONOADMINISTRADOR VARCHAR(200),
    CEDULAADMINISTRADOR  VARCHAR(200)UNIQUE,
	CORREOADMINISTRADOR VARCHAR(200)
); 

CREATE TABLE MECANICO (
    IDMECANICO INT IDENTITY PRIMARY KEY,
    NOMBREMECANICO VARCHAR(200),
    TELEFONOMECANICO VARCHAR(200),
    CEDULAMECANICO VARCHAR(200)UNIQUE,
	CORREOMECANICO VARCHAR(200)
);

CREATE TABLE SERVICIOS (
    IDSERVICIOS INT IDENTITY PRIMARY KEY,
	IDMECANICO INT,
    NOMBRESERVICIO VARCHAR(255),
	FECHASERVICIO DATE,
	CAMPOSERVICIO VARCHAR(6)
	CHECK (CAMPOSERVICIO IN ('MAÑANA', 'TARDE')),
    PRECIOSERVICIO DECIMAL(18, 2)
);

CREATE TABLE Temp_DETALLEVENTA (
    IDDETALLEVENTA INT IDENTITY PRIMARY KEY,
    IDFACTURAVENTA INT,
    IDREFACCION INT,
    CANTIDAD INT,
    IDSERVICIOS INT,
    SUBTOTAL INT
);

CREATE TABLE FACTURAVENTA (
    IDFACTURAVENTA INT IDENTITY PRIMARY KEY,
    IDADMINISTRADOR INT,
    FECHA DATE DEFAULT GETDATE(), 
    IDCLIENTE INT,
	TOTALVENTA DECIMAL(10,2)
);


CREATE TABLE DETALLEVENTA (
    IDDETALLEVENTA INT IDENTITY PRIMARY KEY,
    IDFACTURAVENTA INT,
    IDREFACCION INT,
    CANTIDAD INT,
    IDSERVICIOS INT,
    SUBTOTAL INT
);


CREATE TABLE FACTURACOMPRA (
    IDFACTURACOMPRA INT IDENTITY PRIMARY KEY,
    IDADMINISTRADOR INT,
    FECHA DATE DEFAULT GETDATE(),
	TOTALCOMPRA DECIMAL(10,2)
);


CREATE TABLE DETALLECOMPRA (
    IDDETALLECOMPRA INT PRIMARY KEY,
    IDFACTURACOMPRA INT,
    IDREFACCION INT,
    CANTIDAD int,
    SUBTOTAL Decimal(10,2)
);

CREATE TABLE REFACCION (
    IDREFACCION INT IDENTITY PRIMARY KEY,
    CODIGO_REFACCION VARCHAR(255) UNIQUE,
    NOMBREREFACCION VARCHAR(255),
    PRECIOREFACCION FLOAT
);

CREATE TABLE INVENTARIO (
    IDINVENTARIO INT IDENTITY PRIMARY KEY,
    IDREFACCION INT,
    CANTIDAD INT
);


CREATE TABLE CARRO (
    IDCARRO INT IDENTITY PRIMARY KEY,
    IDCLIENTE INT,
    MARCA VARCHAR(255),
    PLACA VARCHAR(255)
);
-- tabla temoral para cargar datos
CREATE TABLE TEMPCargaDetallesCompra (
    ID INT IDENTITY PRIMARY KEY,
    IDFACTURACOMPRA INT,
    IDREFACCION INT,
    CANTIDAD int,
    SUBTOTAL Decimal(10,2)
);




-- CREACION DE LAS RELACIONES
ALTER TABLE CARRO ADD CONSTRAINT FK_CAR
	FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);
	--
	-- 
ALTER TABLE SERVICIOS ADD CONSTRAINT FK_MECAMECA
	FOREIGN KEY (IDMECANICO) REFERENCES MECANICO(IDMECANICO);
	--
ALTER TABLE FACTURAVENTA ADD CONSTRAINT FK_FACVENT
	FOREIGN KEY (IDADMINISTRADOR) REFERENCES ADMINISTRADOR(IDADMINISTRADOR);
	--
ALTER TABLE FACTURACOMPRA ADD CONSTRAINT FK_FACCOMP
	FOREIGN KEY (IDADMINISTRADOR) REFERENCES ADMINISTRADOR(IDADMINISTRADOR);
	--
ALTER TABLE FACTURAVENTA ADD CONSTRAINT FK_FACVENCLIE
	FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);
	--
ALTER TABLE DETALLEVENTA ADD CONSTRAINT FK_DETVENT
	FOREIGN KEY (IDFACTURAVENTA) REFERENCES FACTURAVENTA(IDFACTURAVENTA);
	--
ALTER TABLE DETALLECOMPRA ADD CONSTRAINT FK_DETCOMPRA
	FOREIGN KEY (IDFACTURACOMPRA) REFERENCES FACTURACOMPRA(IDFACTURACOMPRA);
	--
	--
ALTER TABLE INVENTARIO ADD CONSTRAINT FK_INVNTARIO
	FOREIGN KEY (IDREFACCION) REFERENCES REFACCION(IDREFACCION);
	--
ALTER TABLE DETALLECOMPRA ADD CONSTRAINT FK_DETREFAC
	FOREIGN KEY (IDREFACCION) REFERENCES REFACCION(IDREFACCION);
		--


	

	INSERT INTO CLIENTE (NOMBRECLIENTE, TELEFONOCLIENTE, CEDULACLIENTE, CORREOCLIENTE)
VALUES
    ('Lucia', '123456789', '1234567890', 'cliente1@example.com'),
    ('Jose', '987654321', '0987654321', 'cliente2@example.com'),
    ('Miguel', '456789123', '4567890123', 'cliente3@example.com');

-- Registros para la tabla ADMINISTRADOR
INSERT INTO ADMINISTRADOR (NOMBREADMINISTRADOR, TELEFONOADMINISTRADOR, CEDULAADMINISTRADOR, CORREOADMINISTRADOR)
VALUES
    ('Carlos', '111222333', '1112223330', 'admin1@example.com'),
    ('Roberto', '444555666', '4445556660', 'admin2@example.com'),
    ('Julio', '777888999', '7778889990', 'admin3@example.com');

-- Registros para la tabla MECANICO
INSERT INTO MECANICO (NOMBREMECANICO, TELEFONOMECANICO, CEDULAMECANICO, CORREOMECANICO)
VALUES
    ('Juan', '555666777', '5556667770', 'mecanico1@example.com'),
    ('Federico', '888999000', '8889990000', 'mecanico2@example.com'),
    ('Mariano', '222333444', '2223334440', 'mecanico3@example.com');


	INSERT INTO REFACCION (CODIGO_REFACCION, NOMBREREFACCION, PRECIOREFACCION) VALUES
('#REF-1', 'Batería de automóvil', 65000),
('#REF-2', 'Filtro de aire', 12000),
('#REF-3', 'Filtro de aceite', 8500),
('#REF-4', 'Pastillas de freno delanteras', 9000),
('#REF-5', 'Pastillas de freno traseras', 10000),
('#REF-6', 'Disco de freno delantero', 35000),
('#REF-7', 'Disco de freno trasero', 40000),
('#REF-8', 'Amortiguador delantero', 42000),
('#REF-9', 'Amortiguador trasero', 39590),
('#REF-10', 'Kit de embrague', 125000),
('#REF-11', 'Bomba de agua', 50000),
('#REF-12', 'Correa de distribución', 15000),
('#REF-13', 'Termostato', 12500),
('#REF-14', 'Sensor de oxígeno', 6000),
('#REF-15', 'Sensor de velocidad (ABS)', 22000),
('#REF-16', 'Bobina de encendido', 18000),
('#REF-17', 'Bujías', 7000),
('#REF-18', 'Radiador', 85000),
('#REF-19', 'Alternador', 95000),
('#REF-20', 'Motor de arranque', 70000);


-- Insertar registros para el mecánico 1
INSERT INTO SERVICIOS (IDMECANICO, NOMBRESERVICIO, FECHASERVICIO, CAMPOSERVICIO, PRECIOSERVICIO)
VALUES
    (1, 'Servicio 1', '2023-09-08', 'MAÑANA', 50000.00),
    (1, 'Servicio 2', '2023-09-08', 'TARDE', 60000.00),
    (1, 'Servicio 3', '2023-09-07', 'MAÑANA', 55000.00),
    (1, 'Servicio 4', '2023-09-06', 'MAÑANA', 50000.00),
    (1, 'Servicio 5', '2023-09-05', 'MAÑANA', 60000.00);

-- Insertar registros para el mecánico 2
INSERT INTO SERVICIOS (IDMECANICO, NOMBRESERVICIO, FECHASERVICIO, CAMPOSERVICIO, PRECIOSERVICIO)
VALUES
    (2, 'Servicio 1', '2023-09-08', 'TARDE', 50000.00),
    (2, 'Servicio 2', '2023-09-07', 'TARDE', 60000.00),
    (2, 'Servicio 3', '2023-09-06', 'TARDE', 55000.00),
    (2, 'Servicio 4', '2023-09-05', 'TARDE', 50000.00),
    (2, 'Servicio 5', '2023-09-04', 'TARDE', 6000.00);

-- Insertar registros para el mecánico 3
INSERT INTO SERVICIOS (IDMECANICO, NOMBRESERVICIO, FECHASERVICIO, CAMPOSERVICIO, PRECIOSERVICIO)
VALUES
    (3, 'Servicio 1', '2023-09-08', 'MAÑANA', 55000.00),
    (3, 'Servicio 2', '2023-09-07', 'MAÑANA', 50000.00),
    (3, 'Servicio 3', '2023-09-06', 'MAÑANA', 60000.00),
    (3, 'Servicio 4', '2023-09-05', 'MAÑANA', 55000.00),
    (3, 'Servicio 5', '2023-09-04', 'MAÑANA', 50000.00);



	SELECT A.NOMBREADMINISTRADOR AS Administrador, C.NOMBRECLIENTE AS Cliente,  
	F.FECHA AS Fecha,  F.TOTALVENTA AS TotalVenta FROM FACTURAVENTA F 
	INNER JOIN ADMINISTRADOR A ON F.IDADMINISTRADOR = A.IDADMINISTRADOR 
	INNER JOIN CLIENTE C ON F.IDCLIENTE = C.IDCLIENTE

	SELECT A.NOMBREADMINISTRADOR AS Administrador, C.NOMBRECLIENTE AS Cliente,  
       F.FECHA AS Fecha, F.TOTALVENTA AS TotalVenta
FROM FACTURAVENTA F 
INNER JOIN ADMINISTRADOR A ON F.IDADMINISTRADOR = A.IDADMINISTRADOR 
INNER JOIN CLIENTE C ON F.IDCLIENTE = C.IDCLIENTE
WHERE F.TOTALVENTA IS NOT NULL;

